---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'


platforms:
  #- name: ubuntu-12.04
  - name: centos-6.5
    driver:
      vagrantfile_erb: Vagrantfile.erb


suites:
  - name: default
    run_list:
      - recipe[timezone-ii]
      - recipe[java@1.31.0]
      - recipe[build-essential]
      - recipe[r-compiledfromsource]
      - recipe[r31bioc214::default]
    attributes:
      ubuntu:
        mirror_site_url: http://ftp.jaist.ac.jp/pub/Linux/ubuntu/
        version: 12.04
        need_deb_src: false
        need_update: true
      tz: "Asia/Tokyo"
      r_compiledfromsource:
        sourceurl: "ftp://ftp.stat.math.ethz.ch/Software/CRAN/src/base/R-3/R-3.1.2.tar.gz"
        install_directory: "/usr/local/R/3.1.2"
      r31bioc214:
        r_prefix_path: "/usr/local/R/3.1.2/bin/"
      java:
        install_flavor: "oracle"
        jdk_version: 8
        oracle:
          accept_oracle_download_terms: true


